travis:
  secure:
    BINSTAR_TOKEN: QMz3YoRwu2vHug1I5jLA9Sm6cAn+N42E68iwMmjv1cK6brOVhAPi7fnaqJ74FHC34oyUq26PpGkZ/oKtkA4x//ZS4Ex9AflQNaHV7J08MtQ94DxIUk65t35pPcu4qS0qy4kGPItMGY5p8p0r/4QsE25YZIcNogno8Vk6uShEYKxtvIQpKyBBnq9cbzaK1QjtWR45rRQzQYu09WIE1rqQTrXsUg3L7bcTbQ9t6ZEDJWnLJvP4LR46QrSxOgZ2kph2HfzV29JYHpeC2CTgH4aSfSH9CS/iD/xJvPOWk+tPkIlJOxd+ezvnbe4YMSCufOf4R4ZUEF2spHct6ZhOYiuYMhbNyBPKxqT+sZyITPS5pvuKk37KWrVoyF3d6tsYLKTG2SpUjPWC+Kg1nKRKeT1GUtPhVGnffX4NnTwba6LedYkFXFwXrBE1U10TvzaQimK01DXX5e3o7F7LxAIH0IHFKIrIQ82EidpnpVBvopqdMNKwTrFriNJ2nQv/NY7XO+VR7NYHw4b6+waYWQxljXU1QTQn80zrIqHQkHbQNuL+0e2dg7WVbFkqCqqMBEo33yqEFXiMMqPvvQCsY0OT+4CClkvQQzs577ebOmwPOg+nTSNoNZGlMEOgNtF5SiyrIcBg4wWDdBwpdfNkiPqG3m+Z6SIgDRaUehMOGebwL4mzoV4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
